### ISSUE TITLE
Inquire about how to use the library.

### ISSUE THREAD

**Issue by WORLD8848** [OneUIProject/sesl#4]
Hello.

I would like to apply Sesl Library to the project. I am inquiring about this.

### **Here's the first question.**
I would like to apply Sesl library.

In the settings.gradle file,
  include ':SESL'
  project (':SESL').projectDir    = new File('_File Path_')

In the build.gradle file,
  implementation project(':SESL')

The following is an error message.

### Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file '../SESL/build.gradle'

Have you ever experienced such an error message? If you have, please share your experiences.

Here's the second question.

I want to add only specific libraries within the sesl library, not the entire sesl library.  Do you have any recommendations for this idea?

I know that you have a lot of trouble to upgrade the project. Thank you very much.
I'm sorry to bother you with the question, but please answer it.

**Comment by BlackMesa123** [comment]
Why not just add the dependencies in your build.gradle file? The peculiarity of these new libs is exactly to have each component separated in its own module like in Google libraries, so you can decide what to use:
```groovy
dependencies {
    // AppCompat
    implementation 'io.github.oneuiproject.sesl:appcompat:1.0.0'
    // Material Components
    implementation 'io.github.oneuiproject.sesl:material:1.0.0'
    // SwipeRefresh
    implementation 'io.github.oneuiproject.sesl:swiperefreshlayout:1.0.0'
    // and so on...
}
```
If you really want to implement the whole lib source in your project (I don't see why tho) you can't just copy the whole project in a separate folder, since every folder is a module and you have to import each one ([settings.gradle](https://github.com/OneUIProject/sesl/blob/main/settings.gradle), [build.gradle](https://github.com/OneUIProject/sesl/blob/b272d5efceee520f1529508c8373864a340801f2/picker/picker-basic/build.gradle#L26))

**Comment by WORLD8848** [comment]
Hello. Thank you very much for your answer to the above questions.

I fully understand how to add dependencies in how to use the library.
I understand that the purpose of this library is to enable Samsung UX elements to be learned, adapted, or used for any purpose suitable for you.

I think there are various users who want to use the library. So I asked you to think of other ways besides the way mentioned above. I think the quality of the library can meet the requirements of various developers? I think you can fully relate to this part.


I am truly grateful for your reply.
